Update wercker.yml

diff --git a/wercker.yml b/wercker.yml
--- a/wercker.yml
+++ b/wercker.yml
@@ -154,5 +154,22 @@ test:
             
             ant -diagnostics
             sudo cd ./test/functional/WhackaPodUIAuto
-            ant -file getip.xml
-            ant -file checkbuild.xml
+            ant -f getip.xml -logfile getip.log
+            
+            RETURN=`cat getip.log | grep "FAILED" | wc -l`
+            if [ ${RETURN} -eq "0" ]; then
+	                 echo "Get IP PASS!"
+	                 exit 0
+            else
+	                 echo "GET IP FAIL!"
+	                 exit 1
+            fi
+            ant -f checkbuild.xml -logfile checktext.log
+            RETURN=`cat checktext.log | grep "FAILED" | wc -l`
+            if [ ${RETURN} -eq "0" ]; then
+	                 echo "check text PASS!"
+	                 exit 0
+            else
+	                 echo "check text FAIL!"
+	                 exit 1
+            fi
